export const F = {
	display: "'Epilogue', sans-serif",
	heading: "'Epilogue', sans-serif",
	body: "'Plus Jakarta Sans', sans-serif",
	label: "'Plus Jakarta Sans', sans-serif",
	mono: "'Plus Jakarta Sans', sans-serif",
};

export const C = {
	primary: "#2A9D8F",
	primaryContainer: "#2A9D8F",
	onPrimary: "#ffffff",
	secondary: "#1B2A4A",
	secondaryContainer: "#1B2A4A",
	tertiary: "#E9C46A",
	tertiaryFixed: "#E9C46A",
	surface: "#FAFAF7",
	surfaceLow: "#F3F1ED",
	surfaceHigh: "#ECE9E2",
	surfaceHighest: "#E4DFD3",
	surfaceLowest: "#ffffff",
	outline: "#8E8A80",
	outlineVariant: "#D9D4C8",
	textMain: "#1a1c1b",
	textMuted: "#3d4947",
	textSubtle: "#6d7a77",
	white: "#ffffff",
	teal: "#2A9D8F",
	navy: "#1B2A4A",
	gold: "#E9C46A",
	cream: "#FAFAF7",
	warmGray: "#F3F1ED",
	text1: "#1a1c1b",
	text2: "#3d4947",
	text3: "#6d7a77",
	border: "#bcc9c6",
	green: "#059669",
	red: "#ba1a1a",
};
